services:

  postgres:
    image: postgres:16
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: marketplace-redis
    ports:
      - "6380:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=marketplace;Username=postgres;Password=postgres"
      Redis__ConnectionString: "redis:6379"
    depends_on:
      - postgres
      - redis